name: Clojure CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compile app
      run: npm compile
    - name: run prod
      run: npm run release
